"TimeUTC","timestampInMs","requestPath","requestMethod","requestQueryString","responseStatusCode","requestId","requestUserAgent","level","environment","branch","vercelCache","type","function","host","deploymentDomain","deploymentId","durationMs","region","maxMemoryUsed","memorySize","message","projectId","traceId","sessionId"
"2025-05-18 03:15:29",1747538129363,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"nfx72-1747538128741-c07b5e7b4743","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:15:28",1747538128798,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"nfx72-1747538128741-c07b5e7b4743","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",530,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:13:32",1747538012686,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"dstgv-1747538012073-153a20e5dd8a","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:13:32",1747538012131,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"dstgv-1747538012073-153a20e5dd8a","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",539,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:12:11",1747537931002,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"d2m7f-1747537930211-9c591d322356","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:12:10",1747537930413,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"d2m7f-1747537930211-9c591d322356","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",565,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:10:27",1747537827155,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"nfsb6-1747537826451-d94aa56182f9","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:10:26",1747537826512,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"nfsb6-1747537826451-d94aa56182f9","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",618,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:08:26",1747537706395,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"d9kpv-1747537705583-42661c481809","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:08:25",1747537705808,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"d9kpv-1747537705583-42661c481809","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",533,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:06:55",1747537615525,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"gp7c9-1747537614906-675cc1c75086","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:06:54",1747537614963,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"gp7c9-1747537614906-675cc1c75086","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",543,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:05:15",1747537515848,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"nkpgm-1747537515233-1147c058eb40","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:05:15",1747537515302,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"nkpgm-1747537515233-1147c058eb40","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",525,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:04:03",1747537443176,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"dqtmd-1747537442357-719584cd991d","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:04:02",1747537442533,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"dqtmd-1747537442357-719584cd991d","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",616,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:02:56",1747537376301,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"wjh82-1747537375732-c216512f40ab","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:02:55",1747537375789,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"wjh82-1747537375732-c216512f40ab","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",487,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:00:56",1747537256673,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"5ftxk-1747537255905-2438469b8543","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 03:00:56",1747537256106,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"5ftxk-1747537255905-2438469b8543","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",547,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:59:07",1747537147848,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"qkdkg-1747537146979-81b8c2c5a348","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:59:07",1747537147321,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"qkdkg-1747537146979-81b8c2c5a348","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",508,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:16",1747537096068,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.png","GET","",-1,"rcttj-1747537095515-52866f05fb0b","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:15",1747537095562,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.png","GET","",500,"rcttj-1747537095515-52866f05fb0b","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",490,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:13",1747537093460,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.png","GET","",-1,"ztrdg-1747537092910-e23dfe256590","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:13",1747537093223,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.png","GET","",-1,"psmzz-1747537092679-d17307b36578","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:12",1747537092952,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.png","GET","",500,"ztrdg-1747537092910-e23dfe256590","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",490,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:12",1747537092721,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.png","GET","",500,"psmzz-1747537092679-d17307b36578","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",484,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:11",1747537091821,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.png","GET","",-1,"jhbv5-1747537091242-e53d0f345eda","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:11",1747537091285,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.png","GET","",500,"jhbv5-1747537091242-e53d0f345eda","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",519,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:11",1747537091191,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",-1,"c89gn-1747537090602-fe5660602feb","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:10",1747537090644,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",500,"c89gn-1747537090602-fe5660602feb","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",530,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:10",1747537090574,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.png","GET","",-1,"6kqxt-1747537089996-d5fe72cde651","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:10",1747537090038,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.png","GET","",500,"6kqxt-1747537089996-d5fe72cde651","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",518,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:08",1747537088903,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.png","GET","",-1,"qtdnk-1747537088336-816403e94a32","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:08",1747537088550,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",-1,"q4b6j-1747537087950-4477283f602e","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:08",1747537088379,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.png","GET","",500,"qtdnk-1747537088336-816403e94a32","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",503,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:08",1747537088293,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.ico","GET","",-1,"sv6r5-1747537087719-3d858ac3443a","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:08",1747537088004,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",500,"q4b6j-1747537087950-4477283f602e","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",527,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:07",1747537087773,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.ico","GET","",500,"sv6r5-1747537087719-3d858ac3443a","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",493,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:06",1747537086849,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",-1,"5vbg2-1747537086281-5413ff1fd87c","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:06",1747537086327,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",500,"5vbg2-1747537086281-5413ff1fd87c","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",504,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:06",1747537086131,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",-1,"zs4lq-1747537085549-6b9710b942e3","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:05",1747537085595,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.ico","GET","",-1,"ktvds-1747537085025-8206bc9a2475","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:05",1747537085593,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",500,"zs4lq-1747537085549-6b9710b942e3","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",519,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:05",1747537085069,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.ico","GET","",500,"ktvds-1747537085025-8206bc9a2475","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",508,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:04",1747537084458,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",-1,"9ljnd-1747537083876-b4e2d30b43f8","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083919,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",500,"9ljnd-1747537083876-b4e2d30b43f8","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",519,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083886,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.ico","GET","",-1,"v2zm8-1747537083332-497164a702de","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083750,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",-1,"6kqxt-1747537083166-45e0ecc3f7a5","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083382,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/favicon.ico","GET","",500,"v2zm8-1747537083332-497164a702de","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",489,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083231,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",500,"6kqxt-1747537083166-45e0ecc3f7a5","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",501,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083208,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/","GET","",-1,"kq9d2-1747537082640-7963515138e9","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:03",1747537083026,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",-1,"khf6n-1747537082354-c4a64c595098","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:02",1747537082904,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",-1,"85v7j-1747537082339-12e7853696ab","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:02",1747537082692,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/","GET","",500,"kq9d2-1747537082640-7963515138e9","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",502,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:02",1747537082509,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",500,"khf6n-1747537082354-c4a64c595098","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",495,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:02",1747537082388,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/favicon.ico","GET","",500,"85v7j-1747537082339-12e7853696ab","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",498,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:02",1747537082234,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",-1,"h5kbl-1747537080876-570aa32c9aa3","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"els import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:02",1747537082182,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",-1,"pls9h-1747537081517-2cbeaa830211","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:01",1747537081665,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",500,"pls9h-1747537081517-2cbeaa830211","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",498,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:01",1747537081526,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/","GET","",-1,"9f74j-1747537080854-d2b889d43fb2","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:01",1747537081403,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",-1,"xzf6f-1747537080581-8249cf78c717","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:01",1747537081027,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",500,"h5kbl-1747537080876-570aa32c9aa3","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",496,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:01",1747537081016,"ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app/","GET","",500,"9f74j-1747537080854-d2b889d43fb2","Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","ai-screenshot-manage-17may5pm-mlmb5s8p4.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",481,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:58:00",1747537080878,"ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app/","GET","",500,"xzf6f-1747537080581-8249cf78c717","vercel-screenshot/1.0","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","ai-screenshot-manage-17may5pm-ppd1taoeg.vercel.app","dpl_4X7eob5SZcK2c6N9WL6dTxYEc7iC",509,"iad1",63,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:57:57",1747537077920,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"f958n-1747537077335-dd28fa841bd0","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:57:57",1747537077393,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"f958n-1747537077335-dd28fa841bd0","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",505,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:56:33",1747536993280,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"gkcs9-1747536992653-809901bf429c","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:56:32",1747536992710,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"gkcs9-1747536992653-809901bf429c","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",551,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:54:56",1747536896598,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"858jc-1747536896033-ba0243f1117a","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:54:56",1747536896094,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"858jc-1747536896033-ba0243f1117a","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",478,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:53:34",1747536814978,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"sxbhd-1747536814420-a4ed5492f3ec","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:53:34",1747536814479,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"sxbhd-1747536814420-a4ed5492f3ec","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",481,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:52:29",1747536749364,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"ndvpz-1747536748705-d96ef06acf74","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:52:28",1747536748785,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"ndvpz-1747536748705-d96ef06acf74","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",555,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:50:38",1747536638648,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"t68l6-1747536638020-5810d364bf79","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:50:38",1747536638140,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"t68l6-1747536638020-5810d364bf79","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",487,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:48:38",1747536518963,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"fw4dr-1747536518360-b18bfcb718c8","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:48:38",1747536518418,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"fw4dr-1747536518360-b18bfcb718c8","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",520,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:46:48",1747536408305,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",-1,"bv8qs-1747536407733-a121c9267e51","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/simple_server.py"", line 1, in <module>
from fastapi import FastAPI, Request, Body, HTTPException
File ""/var/task/fastapi/__init__.py"", line 7, in <module>
from .applications import FastAPI as FastAPI
File ""/var/task/fastapi/applications.py"", line 15, in <module>
from fastapi import routing
File ""/var/task/fastapi/routing.py"", line 24, in <module>
from fastapi.dependencies.models import Dependant
File ""/var/task/fastapi/dependencies/models.py"", line 3, in <module>
from fastapi.security.base import SecurityBase
File ""/var/task/fastapi/security/__init__.py"", line 1, in <module>
from .api_key import APIKeyCookie as APIKeyCookie
File ""/var/task/fastapi/security/api_key.py"", line 3, in <module>
from fastapi.openapi.models import APIKey, APIKeyIn
File ""/var/task/fastapi/openapi/models.py"", line 103, in <module>
class Schema(BaseModel):
File ""/var/task/pydantic/main.py"", line 287, in __new__
cls.__try_update_forward_refs__()
File ""/var/task/pydantic/main.py"", line 809, in __try_update_forward_refs__
update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
File ""/var/task/pydantic/typing.py"", line 553, in update_model_forward_refs
update_field_forward_refs(f, globalns=globalns, localns=localns)
File ""/var/task/pydantic/typing.py"", line 519, in update_field_forward_refs
field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/var/task/pydantic/typing.py"", line 65, in evaluate_forwardref
return cast(Any, type_)._evaluate(globalns, localns, set())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
"2025-05-18 02:46:47",1747536407789,"ai-screenshot-manage-17may5pm.vercel.app/api/v1/webhook","POST","",500,"bv8qs-1747536407733-a121c9267e51","-","error","production","main","MISS","lambda","/simple_server.py","ai-screenshot-manage-17may5pm.vercel.app","ai-screenshot-manage-17may5pm.vercel.app","dpl_A4oiNkWDe4qgoMqi6rSS3zqh9yGq",495,"iad1",64,1024,"","prj_aiBy5kVgHhyaHWKPCGPoFjn1iwD0","",""
